INSERT INTO public.book(author, cover_url, description, isbn, status, title, total_page, year_published)
VALUES ('Martin, George R. R.',
'http://4.bp.blogspot.com/-AUo8qpbmCrI/TcaTaw9daVI/AAAAAAAACnA/cattreziXIc/s1600/capa_a_tormenta_de_espadas_frente.jpg',
'A tormenta de espadas, o terceiro livro da série de George R. R. Martin, onde os Sete Reinos já sentem o rigoroso inverno que chega, mas as batalhas parecem estar mais cruéis e impiedosas. Enquanto os Sete Reinos estremecem com a chegada dos temíveis selvagens pela Muralha, numa maré interminável de homens, gigantes e terríveis bestas, Jon Snow, o Bastardo de Winterfell, que se encontra entre eles, divide-se entre sua consciência e o papel que é forçado a desempenhar. Robb Stark, o Jovem Lobo, vence todas as suas batalhas, mas será que ele conseguirá vencer os desafios que não se resolvem apenas com a espada? Arya continua a caminho de Correrrio, mas mesmo alguém tão desembaraçado como ela terá grande dificuldade em ultrapassar os obstáculos que se aproximam. Na corte de Joffrey, em Porto Real, Tyrion luta pela vida, depois de ter sido gravemente ferido na Batalha da Água Negra; e Sansa, livre do compromisso com o homem que agora ocupa o Trono de Ferro, precisa lidar com as consequências de ser a segunda na linha de sucessão de Winterfell, uma vez que Bran e Rickon estariam mortos. No Leste, Daenerys Targaryen navega em direção às terras da sua infância, mas antes ela precisará aportar às desprezíveis cidades dos esclavagistas. Mas a menina indefesa agora é uma mulher poderosa. Quem sabe quanto tempo falta para se transformar em uma conquistadora impiedosa?',
'9788580442625', 'PUBLISHED', 'A Tormenta de Espadas - As Crônicas de Gelo e Fogo - Vol. 3', 884, '2011');

INSERT INTO public.book(author, cover_url, description, isbn, status, title, total_page, year_published)
VALUES ('Martin, George R. R.',
'http://1.bp.blogspot.com/-YLH08j1gIg4/T2f030JqSkI/AAAAAAAAHuY/UR_KZP2qwqM/s1600/dragoes.jpg',
'O futuro dos Sete Reinos ainda é incerto - novas ameaças e novos inimigos surgem a cada momento. Além do Mar Estreito, Daenerys Targaryen, a última herdeira da Casa Targaryen, governa uma cidade construída sobre o pó e a morte. Mas seus inimigos são cada vez mais numerosos e farão de tudo para destruí-la. Enquanto isso, dois jovens embarcam em missões distintas, mas que podem mudar o destino da Mãe dos Dragões. No Norte, Jon Snow - 998º Senhor Comandante da Patrulha da Noite - fará de tudo para garantir a segurança da Muralha. Para isso, não hesitará em transformar amigos em inimigos e vice-versa. Traições, revelações e um fantasma do passado que volta para assombrar quando menos se espera - em todos os cantos de Westeros e de Essos, mercadores, fora da lei, meistres, reis, nobres, escravos, soldados e troca-peles estão prestes a encarar fatos inesperados. Alguns fracassarão, outros se aproveitarão das forças sombrias que crescem cada vez mais. Mas, neste momento de inquietude crescente, as marés da política e do destino levarão inevitavelmente à maior dança de todas.',
'9788580444810', 'PUBLISHED', 'A Dança Dos Dragões - As Crônicas de Gelo e Fogo – Vol. 5 - Reedição', 864, '2012');


INSERT INTO public.book(author, cover_url, description, isbn, status, title, total_page, year_published)
VALUES ('Rowling, J. K. / Thorne, Jack / Tiffany, John',
'http://s2.glbimg.com/ONjFBGn1-WISdkwZasl0J2lVrvI=/600x900/smart/e.glbimg.com/og/ed/f/original/2016/02/10/harry-potter.png',
'The Eighth Story. Nineteen Years Later. Based on an original new story by J.K. Rowling, Jack Thorne and John Tiffany, a new play by Jack Thorne, Harry Potter and the Cursed Child is the eighth story in the Harry Potter series and the first official Harry Potter story to be presented on stage. The play will receive its world premiere in London’s West End on 30th July 2016. It was always difficult being Harry Potter and it isn’t much easier now that he is an overworked employee of the Ministry of Magic, a husband, and father of three school-age children. While Harry grapples with a past that refuses to stay where it belongs, his youngest son Albus must struggle with the weight of a family legacy he never wanted. As past and present fuse ominously, both father and son learn the uncomfortable truth: sometimes, darkness comes from unexpected places.',
'9780751565355', 'PUBLISHED', 'Harry Potter And The Cursed Child - Parts I & II - Special Uk Rehearsal Edition', 320, '2016');

